# Generated by Django 4.2.16 on 2025-02-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
